name: Docker-ACI-CD

on:
  pull_request:
    branches:
      - main  
    paths:
      - 'api/**'
      - '.github/workflows/cd.yaml'

jobs:
  health-check-job:
    uses: ./.github/workflows/ci.yaml

  build-and-deploy:
    needs: [health-check-job]
    uses: ./.github/workflows/deployment.yaml
    with:
        app_name: apimodeletemplatetest

  delete-resources:
    runs-on: ubuntu-latest
    needs: [health-check-job,build-and-deploy]
    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Delete Azure Container Instance
      uses: azure/CLI@v2
      with:
        azcliversion: 2.61.0
        inlineScript: |
          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
          az container delete --resource-group ${{ secrets.RESSOURCE_GROUP }} --name apimodeletemplatetest --yes